spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cokkiri?serverTimezone=Asia/Seoul&characterEncoding=utf8mb4
    username: admin
    password: apehana1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.character_set: utf8mb4
