spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.165773f0068bd73e
            client-secret: 30224a391cd3cc8fce05a0bd3edc4a7ce104075a
  data:
    web:
      pageable:
        default-page-size: 15
        one-indexed-parameters: true

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  whitelist: /api/users, /api/login, /api/reissue-access-token, /oauth2/authorization/github, /login/oauth2/code/github, /api/items
  authorization-type: Bearer
  access:
    http-header: Authorization
    subject: accessToken
    expiration-time-in-milli-seconds: 3_600_000 # 1000 * 60 * 60 (1hour)
  refresh:
    http-header: Authorization-refresh
    subject: refreshToken
    expiration-time-in-milli-seconds: 5_184_000_000 # 1000 * 60 * 60 * 24 * 60 (60days)
