spring:
  datasource:
    url: jdbc:mysql://localhost:3309/cokkiri_market
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

logging:
  level:
    kr.codesquad:
      DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
spring:
  sql:
    init:
      mode: always

