spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
logging:
  level:
    org:
      springframework:
        security: DEBUG
