spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 425027333105-tlf4daq1d7gu2p4mfpdlbslokl97gg2e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
logging:
  level:
    org:
      springframework:
        security: DEBUG
