version: '1'
services:
  mysql_db:
    image: mysql:8.0
    container_name: second-hand
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: secondhand
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
