version: "3.8"
services:
  app: # 서비스 이름
    container_name: cokkiri-market-app
    image: sudago22/cokkiri-market-app:latest #cicd.yml에서 설정한 이미지 이름
    ports:
      - 8080:8080
    volumes:
      - cokkiri-market-app:/app

  web:
    container_name: cokkiri-market-web
    image: sudago22/cokkiri-market-web:latest
    ports:
      - 5173:5173

  nginx: # 서비스 이름
    container_name: nginx_server
    image: nginx:latest # 최신 버전
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 호스트 경로:컨테이너 경로 연결
    depends_on:
      - app # app 서비스가 실행되어야 nginx 서비스가 실행
      # - web

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email myemail@google.com --agree-tos --no-eff-email -d fishprincess.site
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/logs:/var/log/letsencrypt:rw
      - ./data/certbot/data:/var/www/certbot:rw

volumes:
  cokkiri-market-app: #로컬 또는 서버에 생성되는 폴더 (컨테이너 폴더와 연결)